CREATE DATABASE IF NOT EXISTS LOG_HOPPER_DB;

USE LOG_HOPPER_DB;

DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS CACHE;
DROP TABLE IF EXISTS FILTERS;

CREATE TABLE USERS (
    UserID CHAR(36) NOT NULL DEFAULT (UUID()) PRIMARY KEY,
    userName VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    rolepower INT NOT NULL
);

CREATE TABLE FILTERS (
    FilterID CHAR(36) NOT NULL DEFAULT (UUID()) PRIMARY KEY,
    UserID CHAR(36) REFERENCES USERS(UserID),
    FilterRules TEXT,
    FilterName VARCHAR(255),
    FilterPower VARCHAR(50)
);

CREATE TABLE CACHE (
    CacheID CHAR(36) NOT NULL DEFAULT (UUID()) PRIMARY KEY,
    DateTimeNow DATETIME DEFAULT CURRENT_TIMESTAMP,
    Name VARCHAR(255),
    Content TEXT
);